# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official

# Habilita el uso de librerías AndroidX (Room, Hilt, Compose)
android.useAndroidX=true

# Permite a KSP registrar las clases generadas de Hilt y Room
android.disallowKotlinSourceSets=false